###
GET http://localhost:8083/analytic/client/1

###
GET http://localhost:8083/analytic/courier/1

###
GET http://localhost:8083/analytic/employee/1

###
GET http://localhost:8083/analytic/sum/price/client/1

###
GET http://localhost:8083/analytic/orders/per/month?month=10