###
# Создает заказ
POST localhost:8080/orders
Content-Type: application/json

{
  "clientId": 1,
  "clientName": "Павел",
  "clientPhoneNumber": 123,
  "description": "Повара должны быть",
  "address": "Вологда, ул. мира, д. 99",
  "flat": 12,
  "floor": 3,
  "totalPrice": 100,
  "frontDoor": 2,
  "weight": 100,
  "listDishes": [
    {
      "dishId": 1,
      "dishName": "dfd",
      "quantity": 10
    },
    {
      "dishId": 2,
      "dishName": "dfd",
      "quantity": 10
    },
    {
      "dishId": 3,
      "dishName": "dfd",
      "quantity": 10
    }
  ]
}

###
# Обновляет статус заказа

PUT localhost:8080/orders/27
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
Content-Type: application/json

{
  "status": "REVIEW"
}

###
# Получает все заказы по id клиента
GET localhost:8080/orders/client/1

###
# Получает инфо по id заказа
GET localhost:8080/orders/27