###
# Обновляет статус заказа
PUT http://localhost:8083/orders/5
Content-Type: application/json

{
  "status": "COOKED"
}

###
# Присваивает курьеру заказ
PUT http://localhost:8083/orders/courier
Content-Type: application/json

{
  "id": "4",
  "courierId": "1"
}

###
# Заказы ожидающие курьера
GET http://localhost:8083/orders/awaiting-delivery

###
# Заказы по страницам ожидающие курьера
GET http://localhost:8083/orders/awaiting-delivery/by-page?page=0&pageSize=10

###
# Инфо. о заказе с id _
GET http://localhost:8083/orders/4

###
# Инфо. о куръере с id _
GET http://localhost:8083/orders/courier/2?page=0&pageSize=10

###
# Инфо. о куръере с id _
GET http://localhost:8083/orders/delivering/courier/2
